apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: monolith-cb
  namespace: cinemaabyss
spec:
  host: monolith.cinemaabyss.svc.cluster.local
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 200
      http:
        http1MaxPendingRequests: 200
        maxRequestsPerConnection: 0
    outlierDetection:
      consecutive5xxErrors: 12
      interval: 10s
      baseEjectionTime: 20s
      maxEjectionPercent: 25
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: movies-cb
  namespace: cinemaabyss
spec:
  host: movies-service.cinemaabyss.svc.cluster.local
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 200
      http:
        http1MaxPendingRequests: 200
        maxRequestsPerConnection: 0
    outlierDetection:
      consecutive5xxErrors: 12
      interval: 10s
      baseEjectionTime: 20s
      maxEjectionPercent: 25
